### ISSUE TITLE
What's the requirement of the project?

### ISSUE THREAD

**Issue by ArcherV** [blue-blue272/VideoReID-TCLNet#1]
In the file "train.py", IDE can't find the library as the figure below shows.
![image](https://user-images.githubusercontent.com/13202865/89630938-a6b78c00-d8d2-11ea-9b3c-0ee3b04c3c2f.png)

**Comment by AsuradaYuci** [comment]
@ArcherV  You can find these two transform files in https://github.com/guxinqian/TKP/tree/master/transforms. :)

**Comment by blue-blue272** [comment]
@ArcherV  I have updated the transforms files.
