### ISSUE TITLE
when I run the **ilidsvid** dateset,I got a similar problem.My best result is different from your papers.

### ISSUE THREAD

**Issue by mogeko2333** [blue-blue272/VideoReID-TCLNet#8]
**Extracted features for query set, obtained torch.Size([150, 4096]) matrix
Extracted features for gallery set, obtained torch.Size([150, 4096]) matrix
Extracting features complete in 0m 3s
Computing distance matrix
Computing CMC and mAP
Results ----------
mAP: 77.56%
CMC curve
Rank-1  : 69.33%
Rank-5  : 88.67%
Rank-10 : 92.00%
Rank-20 : 96.67%
------------------
==> Best Rank-1 72.7%, achieved at epoch 100
Finished. Total elapsed time (h:m:s): 0:28:30. Training time (h:m:s): 0:27:31.**

It may be that the training result only used 4 frames. Can you tell me how to use **all the frames** ?
Sorry for any possible interruption.

**Comment by blue-blue272** [comment]
The test is "python test.py --root your path to ilidsvid dataset".  And the dataset to load ilidsvid can be seen https://github.com/guxinqian/AP3D/blob/master/tools/data_manager.py

**Comment by mogeko2333** [comment]
Thank you！I will try.
